name: deploy-dev

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  integration-test:
    uses: ./.github/workflows/integration-test.yaml
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        run: echo "DEPLOYING DEV"
