name: deploy-staging

on: release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    if: "!github.event.release.prerelease"
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        run: echo "DEPLOYING PROD"
